/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "home": [],
    "posts.show": [
        {
            "name": "slug",
            "required": true
        }
    ],
    "login": [],
    "login.callback": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
